spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: hospital
    password: root@123
    url: jdbc:mysql://localhost:3306/hospital
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    spring:
 
  cloud:
      gateway:
        routes:
           - id: DOCTOR-SERVICE
             uri: lb://DOCTOR-SERVICE
             predicates:
                  - Path=/doctor/**
           - id: PATIENT-SERVICE
             uri: lb://PATIENT-SERVICE
             predicates:
                  - Path=/patient/**
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/    
    
